### ISSUE TITLE
0.1.0 Release release-notes

### ISSUE THREAD

**Issue by tusharchou** [tusharchou/local-data-platform#17]
https://pypi.org/project/local-data-platform/
cheers 🍺

_Originally posted by @tusharchou in https://github.com/tusharchou/local-data-platform/issues/16#issuecomment-2383764047_

**Comment by ArpitaDhir** [comment]
Great! How do I access this?

**Comment by tusharchou** [comment]
@ArpitaDhir Acknowledged
