### ISSUE TITLE
0.1.1 Create a Google BigQuery Client 

### ISSUE THREAD

**Issue by tusharchou** [tusharchou/local-data-platform#19]
Use Python's BigQuery API to pull the data from the Near Protocol dataset. For example, this code queries the transactions table and retrieves the data for processing:

## Create a BigQuery client
from google.cloud import bigquery
client = bigquery.Client()

## Define your query to pull data from Near Protocol dataset
query = """
    SELECT *
    FROM `bigquery-public-data.crypto_near.transactions`
    LIMIT 1000;
"""
## Run the query and convert the result to a Pandas DataFrame
query_job = client.query(query)
transactions_df = query_job.to_dataframe()

This retrieves the transaction data, which you can load into Apache Iceberg for storage and further processing.

**Comment by tusharchou** [comment]
@mrutunjay-kinagi picking this up!

**Comment by tusharchou** [comment]
Reviewing now

**Comment by mrutunjay-kinagi** [comment]
Reopening this issue to align with new approach as mentioned in #51

**Comment by mrutunjay-kinagi** [comment]
I'll be working on this. @tusharchou @redpheonixx

**Comment by tusharchou** [comment]
Hi @mrutunjay-kinagi Thanks you for picking this up.

We need a feature to login our credentials as a JSON template for GCP.

So that I can demo to the community

**Comment by tusharchou** [comment]
@mrutunjay-kinagi please create a pr to demo this capability

**Comment by mrutunjay-kinagi** [comment]
Pushed changes in PR #56

**Comment by tusharchou** [comment]
Thank you @mrutunjay-kinagi for working on this, and closing it

**Comment by mrutunjay-kinagi** [comment]
This issue is resolved in PR #86 
@tusharchou @redpheonixx

**Comment by mrutunjay-kinagi** [comment]
> [@mrutunjay-kinagi](https://github.com/mrutunjay-kinagi) what is the blocker on this

This issue is resolved in PR https://github.com/tusharchou/local-data-platform/pull/86 

@tusharchou @redpheonixx @swetadas341

**Comment by tusharchou** [comment]
Thank you
