### ISSUE TITLE
0.1.0 Py version incompatibility

### ISSUE THREAD

**Issue by anushreegupta0043** [tusharchou/local-data-platform#31]
Could not install the library local-data-platform as my system is currently on Py 3.9 version which is older than what's required for the library (error message attached). 

<img width="1030" alt="Screenshot 2024-10-04 at 02 35 49" src="https://github.com/user-attachments/assets/cac6c182-573c-43eb-b3df-e68a6ac10a4a">

**Comment by mrutunjay-kinagi** [comment]
Issue resolved in #34
