### ISSUE TITLE
Add PR and Issue Templates

### ISSUE THREAD

**Issue by mrutunjay-kinagi** [tusharchou/local-data-platform#53]
This issue is to create PR and issue templates for this repository. Templates will help contributors create well-formatted PRs and issues, making it easier for maintainers to review and manage them.

The templates should include the following information:

**PR Template**:
- Title format
- Description format
- Checklist for reviewers

**Issue Template**:
- Title format
- Description format
- Labels and milestones to assign

**Comment by tusharchou** [comment]
picking this up today

**Comment by mrutunjay-kinagi** [comment]
@tusharchou Implemented as part of #54.🚀
